- name: "gather device information from H3C"
  ansible.builtin.raw: display device manuinfo
  register: result

- name: print device info
  debug:
    msg:
      - '{{ result.stdout_lines | select("search", "DEVICE_NAME") | first }}'
      - '{{ result.stdout_lines | select("search", "DEVICE_SERIAL_NUMBER") | first }}'
  register: device_info

- ansible.utils.cli_parse:
    text: "{{ device_info.msg | join(',\n') }}"
    parser:
      name: ansible.netcommon.native
      template_path: templates/display_device_manuinfo.yml
    set_fact: h3c_facts
